---
title: "Sejin EDA"
author: "Joe"
date: "2024-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Packages
```{r packageload,echo=FALSE}
library(readr)
library(dplyr)
library(car)
library(ggplot2)
library(gridExtra)
```

# Data loading
```{r dataload,echo=FALSE}
CNdata_filtered_120123 <- read_csv("CNdata_filtered_120123.csv")
ENdata_filtered_110123 <- read_csv("ENdata_filtered_110123.csv")
```

#2 Original Data preparation

```{r dataprep, echo=FALSE}
#Chinese data, renaming/changing data types to factors
CNdata_filtered_120123$Feed <- CNdata_filtered_120123$feed_typefour
CNdata_filtered_120123$Feed <- as.factor(CNdata_filtered_120123$Feed)
CNdata_filtered_120123$valence <- as.factor(CNdata_filtered_120123$valence)

#Chinese data, selecting relevant variables
Data_CN <- CNdata_filtered_120123 |> 
  dplyr::select(Feed,valence,credavg_all,nwavg_all,share_all,NewsSharing_SM,NewsCred_SM,AI_acceptance,GenTech_op,gender,age) |> 
  mutate(Group = 1)

#English data, adding/renaming relevant variables
ENdata_filtered_110123$NewsCred_SM <- unlist(ENdata_filtered_110123[,255])#rename to match CN data

#English data, selecting relevant variables
Data_EN <-ENdata_filtered_110123 |> 
  dplyr::mutate(valence = feed_valence) |>
  dplyr::mutate(Feed = feedtype_four) |> 
  dplyr::select(Feed,valence,credavg_all,nwavg_all,share_all,NewsSharing_SM,NewsCred_SM,AI_acceptance,GenTech_op,gender,age) |> 
  mutate(Group = 0)

#English data, changing data types to factors
Data_EN$Feed <- as.factor(Data_EN$Feed)
Data_EN$valence <- as.factor(Data_EN$valence)

#one dataframe, Group (1 = Chinese 0 = American)
Data <- rbind(Data_CN,Data_EN)
Data$Group <- as.factor(Data$Group)

#fixing age and gender
Data$age <- 2024 - Data$age
Data$gender <- as.factor(Data$gender)
```

#Time inclusion
```{r}
#Chinese data, renaming/changing data types to factors
CNdata_filtered_120123$Feed <- CNdata_filtered_120123$feed_typefour
CNdata_filtered_120123$Feed <- as.factor(CNdata_filtered_120123$Feed)
CNdata_filtered_120123$valence <- as.factor(CNdata_filtered_120123$valence)

#Chinese data, selecting relevant variables
Data_CN <- CNdata_filtered_120123 |> 
  dplyr::select(Feed,valence,credavg_all,nwavg_all,share_all,Finished,ResponseId,
                NewsSharing_SM,NewsCred_SM,AI_acceptance,GenTech_op,gender,age,Durationinseconds,
                Timer1_ClickCount,Timer1_FirstClick,Timer1_LastClick,Timer1_PageSubmit,
                Timer2_ClickCount,Timer2_FirstClick,Timer2_LastClick,Timer2_PageSubmit,
                Timer3_ClickCount,Timer3_FirstClick,Timer3_LastClick,Timer3_PageSubmit,
                Timer4_ClickCount,Timer4_FirstClick,Timer4_LastClick,Timer4_PageSubmit,
                Timer5_ClickCount,Timer5_FirstClick,Timer5_LastClick,Timer5_PageSubmit,
                Timer6_ClickCount,Timer6_FirstClick,Timer6_LastClick,Timer6_PageSubmit,
                Timer7_ClickCount,Timer7_FirstClick,Timer7_LastClick,Timer7_PageSubmit,
                Timer8_ClickCount,Timer8_FirstClick,Timer8_LastClick,Timer8_PageSubmit) |> 
  mutate(Group = 1)

#English data, adding/renaming relevant variables
ENdata_filtered_110123$NewsCred_SM <- unlist(ENdata_filtered_110123[,255])#rename to match CN data

#English data, selecting relevant variables
Data_EN <-ENdata_filtered_110123 |> 
  dplyr::mutate(valence = feed_valence) |>
  dplyr::mutate(Feed = feedtype_four) |> 
  dplyr::select(Feed,valence,credavg_all,nwavg_all,share_all,Finished,ResponseId,
                NewsSharing_SM,NewsCred_SM,AI_acceptance,GenTech_op,gender,age,Durationinseconds,
                Timer1_ClickCount,Timer1_FirstClick,Timer1_LastClick,Timer1_PageSubmit,
                Timer2_ClickCount,Timer2_FirstClick,Timer2_LastClick,Timer2_PageSubmit,
                Timer3_ClickCount,Timer3_FirstClick,Timer3_LastClick,Timer3_PageSubmit,
                Timer4_ClickCount,Timer4_FirstClick,Timer4_LastClick,Timer4_PageSubmit,
                Timer5_ClickCount,Timer5_FirstClick,Timer5_LastClick,Timer5_PageSubmit,
                Timer6_ClickCount,Timer6_FirstClick,Timer6_LastClick,Timer6_PageSubmit,
                Timer7_ClickCount,Timer7_FirstClick,Timer7_LastClick,Timer7_PageSubmit,
                Timer8_ClickCount,Timer8_FirstClick,Timer8_LastClick,Timer8_PageSubmit) |> 
  mutate(Group = 0)

#English data, changing data types to factors
Data_EN$Feed <- as.factor(Data_EN$Feed)
Data_EN$valence <- as.factor(Data_EN$valence)

#one dataframe, Group (1 = Chinese 0 = American)
Data <- rbind(Data_CN,Data_EN)
Data$Group <- as.factor(Data$Group)

#fixing age and gender
Data$age <- 2024 - Data$age
Data$gender <- as.factor(Data$gender)
```

#3 EDA Start
```{r}
# 3b.i  Does the amount of time spent on the condition (newsfeed) affect the dependent variables (credibility, newsworthiness, shareworthiness)? 

#First,create the 8 unique groups
Data$Feed <- as.numeric(Data$Feed) #making it numeric temporarily to create new variable
Data$Eight <- ifelse(Data$valence==1,Data$Feed,0)
Data$Eight <- as.numeric(Data$Eight) #also numeric temporarily
Data$Eight <- ifelse(Data$valence==2,Data$Feed+4,Data$Eight)

#Returning the two to factors
Data$Feed <- as.factor(Data$Feed)
Data$Eight <- as.factor(Data$Eight)

#Assuming Duration in seconds = best measurement and the top 3 are inactivities, then filter them out?
# Data <- Data |> filter(Durationinseconds < 3601) #max is then 10718 sec = ~3 hrs?

# boxFeed <- ggplot(Data, aes(x=share_all))+geom_violin()+coord_flip()+facet_wrap(~Feed)
# boxFeed <- ggplot(Data, aes(x=credavg_all))+geom_boxplot()+coord_flip()+facet_wrap(~Feed)
# boxFeed <- ggplot(Data, aes(x=nwavg_all))+geom_boxplot()+coord_flip()+facet_wrap(~Feed)

# 3b.ii   Interaction effect: Does a) content types (news, memes, activism, ads) and/or b) valence of news (pos / neg) mediate the effect of credibility (e..g) and time spent on stimuli?
```

##Plot Backups from slides, careful there's a bunch not super labeled sorry
```{r}
Data <- Data |> filter(is.na(Feed)==FALSE)
ggplot(Data, aes(Feed,Durationinseconds))+geom_boxplot(aes(color=Feed))
ggplot(Data, aes(Feed,Durationinseconds))+geom_boxplot(aes(color=valence))
ggplot(Data,aes(Durationinseconds,NewsSharing_SM))+geom_point()+geom_jitter()
ggplot(Data,aes(Durationinseconds,NewsSharing_SM))+geom_point(aes(color=Feed,size=0.8,alpha=.8))
ggplot(Data,aes(Durationinseconds,NewsSharing_SM))+geom_point()+geom_jitter()+coord_flip()
ggplot(Data,aes(Durationinseconds,NewsSharing_SM))+geom_point()+geom_jitter()+coord_flip()
ggplot(Data,aes(log(Durationinseconds),NewsSharing_SM))+geom_point(aes(size=0.3,alpha=0.8,color=Feed))
ggplot(Data,aes(Durationinseconds,credavg_all))+geom_point(aes(size=0.3,alpha=0.8,color=Feed))
```

## Sample Duration Cutoff times
```{r}
#sample thresholds
Time_TwentyMin <- 1200 #seconds
Time_ThirtyMin <- 1800 #seconds
Time_FortyMin <- 2400 #seconds
Time_Hour <- 3600 #seconds
# ------------------------------------
Data_CN <- Data_CN |> # Chinese
  mutate(Twenty_Min_Less = ifelse(Durationinseconds <= Time_TwentyMin,1,0)) |> # Less than or equal to 20 Min
  mutate(Twenty_Min_Plus = ifelse(Durationinseconds > Time_TwentyMin,1,0)) |> # Greater than 20 min
  mutate(Thirty_Min_Plus = ifelse(Durationinseconds > Time_ThirtyMin,1,0)) |> # Greater than 30 min
  mutate(Forty_Min_Plus = ifelse(Durationinseconds > Time_FortyMin,1,0)) |> # Greater than 40 min
  mutate(Hour_Plus = ifelse(Durationinseconds > Time_Hour,1,0)) # Greater than 1 hour

Data_EN <- Data_EN |> # English
  mutate(Twenty_Min_Less = ifelse(Durationinseconds <= Time_TwentyMin,1,0)) |> # Less than or equal to 20 Min
  mutate(Twenty_Min_Plus = ifelse(Durationinseconds > Time_TwentyMin,1,0)) |> # Greater than 20 min
  mutate(Thirty_Min_Plus = ifelse(Durationinseconds > Time_ThirtyMin,1,0)) |> # Greater than 30 min
  mutate(Forty_Min_Plus = ifelse(Durationinseconds > Time_FortyMin,1,0)) |> # Greater than 40 min
  mutate(Hour_Plus = ifelse(Durationinseconds > Time_Hour,1,0)) # Greater than 1 hour

# tried making the following two blocks cleaner using lapply but idk why no work
Data_CN$Twenty_Min_Less <- as.factor(Data_CN$Twenty_Min_Less)
Data_CN$Twenty_Min_Plus <- as.factor(Data_CN$Twenty_Min_Plus)
Data_CN$Thirty_Min_Plus <- as.factor(Data_CN$Thirty_Min_Plus)
Data_CN$Forty_Min_Plus <- as.factor(Data_CN$Forty_Min_Plus)
Data_CN$Hour_Plus <- as.factor(Data_CN$Hour_Plus)

Data_EN$Twenty_Min_Less <- as.factor(Data_EN$Twenty_Min_Less)
Data_EN$Twenty_Min_Plus <- as.factor(Data_EN$Twenty_Min_Plus)
Data_EN$Thirty_Min_Plus <- as.factor(Data_EN$Thirty_Min_Plus)
Data_EN$Forty_Min_Plus <- as.factor(Data_EN$Forty_Min_Plus)
Data_EN$Hour_Plus <- as.factor(Data_EN$Hour_Plus)


#plots Chinese
Plot_Under_20_CN <- ggplot(Data_CN,aes(Twenty_Min_Less)) +
  geom_bar(aes(fill=Twenty_Min_Less))+
  labs(title="Amount of people who spent less than 20 minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Less than 20","20 or more"))+
  theme(legend.title = element_blank())

Plot_Over_20_CN <- ggplot(Data_CN,aes(Twenty_Min_Plus)) +
  geom_bar(aes(fill=Twenty_Min_Less))+
  labs(title="Amount of people who spent 20 or more minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("20 or more","Less than 20"))+
  theme(legend.title = element_blank())

Plot_Over_30_CN <- ggplot(Data_CN,aes(Thirty_Min_Plus)) +
  geom_bar(aes(fill=Thirty_Min_Plus))+
  labs(title="Amount of people who spent more than 30 minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Under 30","Over 30"))+
  theme(legend.title = element_blank())

Plot_Over_40_CN <- ggplot(Data_CN,aes(Forty_Min_Plus)) +
  geom_bar(aes(fill=Forty_Min_Plus))+
  labs(title="Amount of people who spent more than 40 minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Under 40","Over 40"))+
  theme(legend.title = element_blank())

Plot_Over_Hour_CN <- ggplot(Data_CN,aes(Hour_Plus)) +
  geom_bar(aes(fill=Hour_Plus))+
  labs(title="Amount of people who spent more than 1 hour on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Over 1 Hour","Not over 1 Hour"))+
  theme(legend.title = element_blank())


Plot_Under_20_CN
Plot_Over_20_CN
Plot_Over_30_CN
Plot_Over_40_CN
Plot_Over_Hour_CN


#--------------------------------------------------

#plots english
Plot_Under_20_EN <- ggplot(Data_EN,aes(Twenty_Min_Less)) +
  geom_bar(aes(fill=Twenty_Min_Less))+
  labs(title="Amount of people who spent less than 20 minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Less than 20","20 or more"))+
  theme(legend.title = element_blank())

Plot_Over_20_EN <- ggplot(Data_EN,aes(Twenty_Min_Plus)) +
  geom_bar(aes(fill=Twenty_Min_Less))+
  labs(title="Amount of people who spent 20 or more minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("20 or more","Less than 20"))+
  theme(legend.title = element_blank())

Plot_Over_30_EN <- ggplot(Data_EN,aes(Thirty_Min_Plus)) +
  geom_bar(aes(fill=Thirty_Min_Plus))+
  labs(title="Amount of people who spent more than 30 minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Under 30","Over 30"))+
  theme(legend.title = element_blank())

Plot_Over_40_EN <- ggplot(Data_EN,aes(Forty_Min_Plus)) +
  geom_bar(aes(fill=Forty_Min_Plus))+
  labs(title="Amount of people who spent more than 40 minutes on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Under 40","Over 40"))+
  theme(legend.title = element_blank())

Plot_Over_Hour_EN <- ggplot(Data_EN,aes(Hour_Plus)) +
  geom_bar(aes(fill=Hour_Plus))+
  labs(title="Amount of people who spent more than 1 hour on the trial",x="Group",y="Count")+
  scale_fill_hue(labels=c("Under 1 hour","Over 1 Hour"))+
  theme(legend.title = element_blank())


Plot_Under_20_EN
Plot_Over_20_EN
Plot_Over_30_EN
Plot_Over_40_EN
Plot_Over_Hour_EN

# Data$Twenty_Min_Plus <- ifelse(Data$Durationinseconds>timethresh,1,0) would use this to make it for the overall dataset
```

